package docsite

import (
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// Page is one HTML document of the static demo snapshot: the URL to fetch from
// the running server and the file it is written to.
type Page struct {
	URL   string // path incl. query, e.g. "/?sankey=fy"
	File  string // output file name, e.g. "dashboard-fy.html"
	Title string // label used in the demo navigation of the docs site
}

// DemoPages returns every page of the clickable demo snapshot. The dashboard is
// captured once per Sankey horizon so the horizon chips keep working offline.
func DemoPages(week int) []Page {
	pages := []Page{
		{URL: "/", File: "index.html", Title: "Dashboard"},
		{URL: "/projects", File: "projects.html", Title: "Projekte"},
		{URL: fmt.Sprintf("/week/%d", week), File: "week.html", Title: "Forecast"},
		{URL: "/goal", File: "goal.html", Title: "Ziele"},
		{URL: "/settings", File: "settings.html", Title: "Einstellungen"},
	}
	for _, key := range []string{"1w", "2w", "4w", "2m", "3m", "6m", "fy"} {
		pages = append(pages, Page{
			URL:  "/?sankey=" + key,
			File: "dashboard-" + key + ".html",
		})
	}
	for _, weeks := range []int{1, 2, 4} {
		pages = append(pages, Page{
			URL:  fmt.Sprintf("/week/%d?weeks=%d", week, weeks),
			File: fmt.Sprintf("week-%dw.html", weeks),
		})
	}
	return pages
}

// Snapshot fetches every page from the running server and writes a static,
// self-contained copy to outDir: links are rewritten to the local file names,
// the stylesheet is copied along and all writing interactions are neutralised.
func Snapshot(baseURL, outDir string, pages []Page) error {
	if err := os.MkdirAll(filepath.Join(outDir, "static"), 0o750); err != nil {
		return err
	}
	client := &http.Client{Timeout: 30 * time.Second}

	// Map every captured URL to its file name so links between pages keep working.
	byURL := make(map[string]string, len(pages))
	for _, p := range pages {
		byURL[normalizeURL(p.URL)] = p.File
	}

	assets := map[string]bool{}
	for _, p := range pages {
		body, err := fetch(client, baseURL+p.URL)
		if err != nil {
			return fmt.Errorf("snapshot %s: %w", p.URL, err)
		}
		html, refs := rewrite(string(body), byURL)
		for _, a := range refs {
			assets[a] = true
		}
		if err := os.WriteFile(filepath.Join(outDir, p.File), []byte(html), 0o600); err != nil {
			return err
		}
	}

	for asset := range assets {
		body, err := fetch(client, baseURL+asset)
		if err != nil {
			return fmt.Errorf("snapshot asset %s: %w", asset, err)
		}
		name := path.Base(strings.SplitN(asset, "?", 2)[0])
		if err := os.WriteFile(filepath.Join(outDir, "static", name), body, 0o600); err != nil {
			return err
		}
	}
	return nil
}

func fetch(client *http.Client, target string) ([]byte, error) {
	// The target always points at the demo server this process just started.
	resp, err := client.Get(target) //nolint:gosec // local demo server started by this tool
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %s", resp.Status)
	}
	return io.ReadAll(resp.Body)
}

// attrRe matches the URL-carrying attributes of the application's templates.
// Parsing the whole document is unnecessary: the markup is generated by
// html/template and always quotes its attributes with double quotes.
var attrRe = regexp.MustCompile(`(href|action|src)="([^"]*)"`)

var bodyOpenRe = regexp.MustCompile(`(?i)<body[^>]*>`)

// rewrite points every internal link at its snapshot file and returns the
// static assets the page referenced.
func rewrite(html string, byURL map[string]string) (string, []string) {
	var assets []string
	html = attrRe.ReplaceAllStringFunc(html, func(m string) string {
		g := attrRe.FindStringSubmatch(m)
		attr, val := g[1], g[2]
		if !strings.HasPrefix(val, "/") {
			return m // external, anchor or already relative
		}
		if strings.HasPrefix(val, "/static/") {
			assets = append(assets, val)
			return attr + `="static/` + path.Base(strings.SplitN(val, "?", 2)[0]) + `"`
		}
		if file, ok := byURL[normalizeURL(val)]; ok {
			return attr + `="` + file + `"`
		}
		if file, ok := byURL[normalizeURL(fallbackURL(val))]; ok {
			return attr + `="` + file + `"`
		}
		return attr + `="#"`
	})
	html = strings.Replace(html, "</head>", demoHead+"\n</head>", 1)
	html = bodyOpenRe.ReplaceAllStringFunc(html, func(m string) string {
		return m + demoBanner
	})
	html = strings.Replace(html, "</body>", demoScript+"\n</body>", 1)
	return html, assets
}

// fallbackURL maps a link that was not captured to the closest page that was,
// e.g. a link to any fiscal-year week to the single captured week.
func fallbackURL(val string) string {
	p := strings.SplitN(val, "?", 2)[0]
	switch {
	case p == "/" || strings.HasPrefix(p, "/?"):
		return "/"
	case strings.HasPrefix(p, "/week"):
		return "/week"
	case strings.HasPrefix(p, "/projects"):
		return "/projects"
	case strings.HasPrefix(p, "/goal"):
		return "/goal"
	case strings.HasPrefix(p, "/settings"):
		return "/settings"
	}
	return ""
}

// normalizeURL makes two spellings of the same link comparable (sorted query,
// "/week" matching "/week/12").
func normalizeURL(raw string) string {
	if raw == "" {
		return ""
	}
	u, err := url.Parse(raw)
	if err != nil {
		return raw
	}
	p := u.Path
	if strings.HasPrefix(p, "/week/") {
		p = "/week"
	}
	if q := u.Query().Encode(); q != "" {
		return p + "?" + q
	}
	return p
}

const demoHead = `
<style>
.demo-banner{position:sticky;top:0;z-index:50;display:flex;flex-wrap:wrap;align-items:center;gap:.75rem;
  padding:.5rem 1rem;background:#0f172a;color:#e2e8f0;font-size:.85rem}
.demo-banner strong{color:#fff}
.demo-banner a{color:#93c5fd;text-decoration:none}
.demo-banner a:hover{text-decoration:underline}
.demo-banner .spacer{flex:1 1 auto}
</style>`

const demoBanner = `
<div class="demo-banner">
  <strong>Statische Demo</strong>
  <span>Beispieldaten &ndash; Eingaben werden nicht gespeichert.</span>
  <span class="spacer"></span>
  <a href="../index.html">Dokumentation</a>
  <a href="https://github.com/daknoblo/forecast-tool">GitHub</a>
</div>`

// demoScript makes the snapshot inert: there is no server behind it, so every
// form submit and every background save is swallowed instead of producing an
// error page or a red "save failed" pill.
const demoScript = `
<script>
(function () {
  HTMLFormElement.prototype.submit = function () {};
  document.addEventListener('submit', function (e) { e.preventDefault(); }, true);
  window.fetch = function () {
    return Promise.resolve({ ok: true, status: 200, json: function () { return Promise.resolve({ ok: true }); } });
  };
})();
</script>`
